version: '3.5'

services:
  protobuf:
    container_name: protobuf
    build:
      context: ./
      dockerfile: ./protobuf/Dockerfile
    volumes:
      - './backend/src/our_grpc/:/build/py'
      - './frontend/src/grpc:/build/js'
      - './protobuf:/data'
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - protobuf
    volumes:
      - './backend:/data'
    ports:
      - '9090'
    networks:
      - server-net
  envoy:
    container_name: envoy
    build:
      context: ./envoy
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - '7070:7070'
    networks:
      - server-net
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - protobuf
    volumes:
      - './frontend:/data'
      # don't overwrite installed node modules in the container
      - '/data/node_modules'
    ports:
      - '3000:3000'
      # web socket for hot-reload
      - '35729:35729'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - server-net
networks:
  server-net: